module Lrama
  class Grammar
    class Code
      class DestructorCode < Code
        @tag: Lexer::Token::Tag
        def initialize: (type: ::Symbol, token_code: Grammar::Code, tag: Lexer::Token::Tag) -> void

        private

        def reference_to_c: (Reference ref) -> (String | bot)
      end
    end
  end
end
