module Lrama
  class Grammar
    class Code
      class InitialActionCode < Code
        private

        # * ($$) yylval
        # * (@$) yylloc
        # * ($1) error
        # * (@1) error
        def reference_to_c: (Reference ref) -> (String | bot)
      end
    end
  end
end
