module Lrama
  class Grammar
    class Code
      class NoReferenceCode < Code
        private

        # * ($$) error
        # * (@$) error
        # * ($1) error
        # * (@1) error
        def reference_to_c: (Reference ref) -> void
      end
    end
  end
end
