module Lrama
  class Grammar
    class Code
      class PrinterCode < Code
        @tag: untyped
        def initialize: (type: untyped, token_code: untyped, tag: untyped) -> void

        private

        def reference_to_c: (Reference ref) -> (String | bot)
      end
    end
  end
end
