module Lrama
  class Grammar
    class Code
      class RuleAction < Code
        @rule: untyped

        def initialize: (type: ::Symbol, token_code: Grammar::Code, rule: Rule) -> void

        private

        def reference_to_c: (Reference ref) -> String
        def position_in_rhs: () -> Integer
        def rhs: () -> Array[Grammar::Symbol]
        def lhs: () -> Grammar::Symbol
        def raise_tag_not_found_error: (Reference ref) -> bot
      end
    end
  end
end
