module Lrama
  class Grammar
    class ParameterizingRule
      class Rhs
        attr_reader symbols: Array[untyped]
        attr_reader user_code: Lexer::Token::UserCode?
        attr_reader precedence_sym: Grammar::Symbol?

        def initialize: () -> void
        def skip?: (Grammar::Binding bindings) -> bool
        def resolve_symbols: (Grammar::Binding bindings) -> Array[untyped]
        def resolve_user_code: (Grammar::Binding bindings) -> Lexer::Token::UserCode?
      end
    end
  end
end
