module Lrama
  class Grammar
    class ParameterizingRule
      class Rhs
        attr_reader symbols: Array[untyped]
        attr_reader user_code: Lexer::Token::UserCode?
        attr_reader precedence_sym: Lexer::Token?

        def initialize: () -> void
        def resolve_user_code: (Grammar::Binding bindings) -> Lexer::Token::UserCode?
      end
    end
  end
end
