module Lrama
  class Grammar
    class ParameterizingRules
      class Builder
        class Base
          def initialize: (Lexer::Token::Parameterizing token, Counter rule_counter, Lexer::Token::UserCode? user_code, Lexer::Token? precedence_sym, Integer? line) -> void
          def build: () -> Array[Rule]

          @args: Array[Lexer::Token]
          @token: Lexer::Token::Parameterizing
          @key: Symbol
          @rule_counter: Counter
          @lhs: Lexer::Token
          @user_code: Lexer::Token::UserCode?
          @precedence_sym: Lexer::Token?
          @line: Integer?
          @expected_argument_num: Integer

          private

          def validate_argument_number!: () -> void
        end
      end
    end
  end
end
