module Lrama
  class Grammar
    class ParameterizingRules
      class Builder
        class SeparatedNonemptyList < Base
          def initialize: (Lexer::Token token, Counter rule_counter, Lexer::Token lhs, Lexer::Token::UserCode? user_code, Lexer::Token? precedence_sym, Integer? line) -> void
          def build: -> Array[Rule]
        end
      end
    end
  end
end
