module Lrama
  class Grammar
    class ParameterizingRules
      class Builder
        class SeparatedList < Base
          def initialize: (Lexer::Token token, Counter rule_counter, untyped lhs_tag, Lexer::Token::UserCode? user_code, Lexer::Token? precedence_sym, Integer? line) -> void
        end
      end
    end
  end
end
