module Lrama
  class Report
    module Duration
      self.@_report_duration_enabled: bool | nil

      def self.enable: -> void
      def self.enabled?: -> bool
      def report_duration: [T] (_ToS method_name) { -> T } -> T
    end
  end
end
