module Lrama
  class Lexer
    class Token
      attr_accessor s_value: String
      attr_accessor alias: String
      attr_accessor line: Integer
      attr_accessor column: Integer
      attr_accessor referred: bool

      def initialize: (?s_value: String, ?alias: String) -> void

      def to_s: () -> String
      def referred_by?: (String string) -> bool
      def ==: (Token other) -> bool
    end
  end
end
