module Lrama
  class Binding
    attr_reader actual_args: Array[Lexer::Token]
    attr_reader count: Integer

    @parameters: Array[Lexer::Token]
    @parameter_to_arg: untyped

    def initialize: (Array[Lexer::Token] parameters, Array[Lexer::Token] actual_args) -> void
    def resolve_symbol: (Lexer::Token symbol) -> Lexer::Token
  end
end
