module Lrama
  class Warning
    interface _Appendable
      def <<: (String message) -> self
    end

    @out: _Appendable

    attr_reader errors: Array[String]
    attr_reader warns: Array[String]
    def initialize: (?_Appendable out) -> void
    def error: (String message) -> void
    def warn: (String message) -> void
    def has_error?: -> bool
  end
end
