module Lrama
  class Grammar
    class Inline
      class Resolver
        attr_accessor rules: Array[Grammar::Inline::Rule]

        def initialize: () -> void
        def add_inline_rule: (Grammar::Inline::Rule rule) -> void
        def find: (Lexer::Token token) -> Grammar::Inline::Rule?
      end
    end
  end
end
