module Lrama
  class Counterexamples
    class Derivation
      @item: States::Item

      @left: Derivation

      @right: Derivation

      attr_reader item: States::Item

      attr_reader left: Derivation

      attr_reader right: Derivation?

      attr_writer right: Derivation

      def initialize: (States::Item item, Derivation left, ?Derivation? right) -> void

      def to_s: () -> ::String

      alias inspect to_s

      def render_strings_for_report: () -> Array[String]

      def render_for_report: () -> String

      private

      def _render_for_report: (Derivation derivation, Integer offset, Array[String] strings, Integer index) -> Integer
    end
  end
end
