module Lrama
  class Counterexamples
    class Triple
      attr_accessor s: State
      attr_accessor itm: States::Item
      attr_accessor l: Set[Grammar::Symbol]

      alias state s
      alias item itm
      alias precise_lookahead_set l

      def initialize: (State s, States::Item itm, Set[Grammar::Symbol] l) -> void

      def state_item: () -> StateItem
      def inspect: () -> ::String

      alias to_s inspect
    end
  end
end
