module Lrama
  class Counterexamples
    class Triple
      attr_accessor s: untyped
      attr_accessor itm: untyped
      attr_accessor l: untyped

      alias state s
      alias item itm
      alias precise_lookahead_set l

      def initialize: (untyped s, untyped itm, untyped l) -> void

      def state_item: () -> untyped
      def inspect: () -> ::String

      alias to_s inspect
    end
  end
end
