module Lrama
  class Grammar
    class Code
      extend Forwardable

      attr_accessor type: Symbol
      attr_accessor token_code: Lexer::Token::UserCode

      # delegated
      def s_value: -> String
      def line: -> Integer
      def column: -> Integer
      def references: -> Array[Lrama::Grammar::Reference]

      def initialize: (type: Symbol, token_code: Lexer::Token::UserCode) -> void

      def translated_code: () -> String

      private

      def reference_to_c: (untyped ref) -> untyped
    end
  end
end