module Lrama
  class Grammar
    class ErrorToken
      attr_accessor ident_or_tags: Array[Lexer::Token::Ident | Lexer::Token::Tag]
      attr_accessor token_code: Code
      attr_accessor lineno: Integer

      def translated_code: (Lexer::Token::Tag tag) -> String
    end
  end
end
