module Lrama
  class Grammar
    class ParameterizingRuleBuilder
      attr_reader name: String
      attr_reader args: Array[Lexer::Token]
      attr_reader rhs: Array[Grammar::ParameterizingRuleRhsBuilder]

      @required_args_count: Integer

      def initialize: (String name, Array[Lexer::Token] args, Array[Grammar::ParameterizingRuleRhsBuilder] rhs) -> void
      def build_rules: (Lexer::Token::Parameterizing token, Counter rule_counter, untyped lhs_tag, Integer? line) -> Grammar::ParameterizingRule

      private

      def validate_argument_number!: (Lexer::Token::Parameterizing token) -> void
      def lhs_token: (Lexer::Token::Parameterizing token) -> Lexer::Token
      def rhs_token: (Lexer::Token::Parameterizing token, Grammar::ParameterizingRuleRhsBuilder rhs) -> Lexer::Token?
    end
  end
end
