module Lrama
  class Grammar
    class PercentCode
      attr_reader name: String
      attr_reader code: Lexer::Token::UserCode

      def initialize: (String name, Lexer::Token::UserCode code) -> void
    end
  end
end
