module Lrama
  class Grammar
    class PercentCode
      attr_reader id: Lexer::Token::Ident
      attr_reader code: Lexer::Token::UserCode

      def initialize: (Lexer::Token::Ident id, Lexer::Token::UserCode code) -> void
    end
  end
end
