module Lrama
  class Grammar
    class Precedence
      include Comparable
      attr_accessor type: Symbol
      attr_accessor precedence: Integer

      def <=>: (Precedence other) -> Integer
    end
  end
end
