module Lrama
  class Grammar
    class Printer
      attr_accessor ident_or_tags: Array[Lexer::Token::Ident|Lexer::Token::Tag]
      attr_accessor token_code: Grammar::Code
      attr_accessor lineno: Integer

      def translated_code: (Lexer::Token::Tag tag) -> String
    end
  end
end
