module Lrama
  class Grammar
    class Reference
      # TODO: Replace untyped referring_symbol with (Grammar::Symbol|Lexer::Token)
      attr_accessor type: Symbol
      attr_accessor name: String
      attr_accessor index: Integer
      attr_accessor ex_tag: Lexer::Token?
      attr_accessor first_column: Integer
      attr_accessor last_column: Integer
      attr_accessor referring_symbol: untyped
      attr_accessor position_in_rhs: Integer?

      def initialize: (
        type: Symbol, ?name: String, ?index: Integer, ?ex_tag: Lexer::Token?,
        first_column: Integer, last_column: Integer,
        ?referring_symbol: untyped, ?position_in_rhs: Integer?
      ) -> void

      def value: () -> (String|Integer)
      def tag: () -> untyped
    end
  end
end
