module Lrama
  class Grammar
    class Rule
      def initialize: (
        ?id: untyped, ?lhs: untyped, ?rhs: untyped,
        ?token_code: untyped, ?nullable: untyped,
        ?precedence_sym: untyped, ?lineno: untyped
      ) -> void
    end
  end
end
