module Lrama
  class Grammar
    class Rule
      attr_accessor original_rule: Rule

      def initialize: (
        ?id: untyped, ?lhs: untyped, ?rhs: untyped,
        ?token_code: untyped, ?position_in_original_rule_rhs: untyped, ?nullable: untyped,
        ?precedence_sym: untyped, ?lineno: untyped
      ) -> void
    end
  end
end
