module Lrama
  class Grammar
    class Type
      attr_reader id: Lexer::Token
      attr_reader tag: Lexer::Token

      def initialize: (id: Lexer::Token, tag: Lexer::Token) -> void
      def ==: (Grammar::Type other) -> bool
    end
  end
end
