module Lrama
  class Grammar
    class Union
      attr_accessor code: Grammar::Code::NoReferenceCode
      attr_accessor lineno: Integer

      def initialize: (code: Grammar::Code::NoReferenceCode, lineno: Integer) -> void

      def braces_less_code: () -> String
    end
  end
end
