module Lrama
  class States
    class Item
      extend Forwardable

      attr_accessor rule: untyped
      attr_accessor position: Integer

      # Optimization for States#setup_state
      def hash: () -> untyped

      def rule_id: () -> untyped

      def empty_rule?: () -> untyped

      def number_of_rest_symbols: () -> untyped

      def next_sym: () -> untyped

      def next_next_sym: () -> untyped

      def previous_sym: () -> untyped

      def end_of_rule?: () -> untyped

      def beginning_of_rule?: () -> untyped

      def start_item?: () -> untyped

      def new_by_next_position: () -> untyped

      def symbols_before_dot: () -> untyped

      def symbols_after_dot: () -> untyped

      def to_s: () -> ::String

      def display_name: () -> ::String

      # Right after position
      def display_rest: () -> ::String
    end
  end
end
