module Lrama
  class Lexer
    class Token
      class InstantiateRule < Token
        attr_accessor args: Array[Lexer::Token]

        def initialize: (s_value: String, ?alias_name: String, ?location: Location, ?args: Array[Lexer::Token]) -> void
      end
    end
  end
end
