module Lrama
  class Lexer
    class Token
      class Parameterizing < Token
        attr_accessor args: Array[Lrama::Lexer::Token]

        def initialize: (s_value: String, ?alias_name: String, ?location: Location, ?args: Array[Lrama::Lexer::Token]) -> void

        def option?: () -> bool
        def nonempty_list?: () -> bool
        def list?: () -> bool
        def separated_nonempty_list?: () -> bool
        def separated_list?: () -> bool
      end
    end
  end
end
