module Lrama
  class Lexer
    class Token
      attr_accessor type: Type
      attr_accessor s_value: String
      attr_accessor alias: String

      def initialize: (?type: Type, ?s_value: String, ?alias: String) -> void
      class Type
        attr_accessor id: Integer
        attr_accessor name: String

        def initialize: (?id: Integer, ?name: String) -> void
      end
    end
  end
end
