module Lrama
  class Lexer
    class Token
      class UserCode < Token
        def references: () -> Array[Lrama::Grammar::Reference]

        private

        def _references: () -> Array[Lrama::Grammar::Reference]
        def scan_reference: (StringScanner scanner) -> Lrama::Grammar::Reference?
      end
    end
  end
end
