#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "parser.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.7.3'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError # :nodoc:
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is a LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end
module Lrama
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 594)

include Lrama::Report::Duration

def initialize(text, path, debug = false)
  @grammar_file = Lrama::Lexer::GrammarFile.new(path, text)
  @yydebug = debug
  @rule_counter = Lrama::Grammar::Counter.new(0)
  @midrule_action_counter = Lrama::Grammar::Counter.new(1)
end

def parse
  report_duration(:parse) do
    @lexer = Lrama::Lexer.new(@grammar_file)
    @grammar = Lrama::Grammar.new(@rule_counter)
    @precedence_number = 0
    reset_precs
    do_parse
    @grammar
  end
end

def next_token
  @lexer.next_token
end

def on_error(error_token_id, error_value, value_stack)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
    value = "'#{error_value.s_value}'"
  else
    location = @lexer.location
    value = error_value.inspect
  end

  error_message = "parse error on value #{value} (#{token_to_str(error_token_id) || '?'})"

  raise_parse_error(error_message, location)
end

def on_action_error(error_message, error_value)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
  else
    location = @lexer.location
  end

  raise_parse_error(error_message, location)
end

private

def reset_precs
  @prec_seen = false
  @code_after_prec = false
end

def begin_c_declaration(end_symbol)
  @lexer.status = :c_declaration
  @lexer.end_symbol = end_symbol
end

def end_c_declaration
  @lexer.status = :initial
  @lexer.end_symbol = nil
end

def raise_parse_error(error_message, location)
  raise ParseError, location.generate_error_message(error_message)
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    99,    52,   100,    51,    52,    80,   167,    52,    80,    51,
    52,    80,   167,     3,    80,   166,    52,   163,    51,     8,
   169,    71,     6,   163,     7,    52,   169,   215,    42,    80,
    52,    49,   215,    52,    80,    51,   165,    80,    76,    55,
    52,   216,    51,    55,   164,    83,   216,   170,   101,   227,
   164,    55,    52,   170,    51,    58,    80,   189,   190,   191,
    52,    52,    51,    51,    59,    83,    83,    52,   217,    51,
     9,    60,    83,   217,    14,    15,    16,    17,    18,    19,
    61,    62,    20,    21,    22,    23,    25,    26,    27,    28,
    29,    30,    31,    32,    33,    34,    35,    36,    37,    38,
    39,    48,    52,    52,    51,    51,    80,   199,    40,    52,
    52,    51,    51,    80,   199,    52,    52,    51,    51,    80,
   199,    23,    25,    26,    27,    28,    29,    30,    31,    32,
    33,    34,    35,    36,    37,    38,    48,    52,    52,    51,
    51,    94,    80,   199,    52,    52,    51,    51,    80,   199,
    52,    52,    51,    51,    80,   199,    23,    25,    26,    27,
    28,    29,    30,    31,    32,    33,    34,    35,    36,    37,
    38,    52,    52,    51,    51,    80,    80,    52,    52,    51,
    51,    80,    80,    52,    52,    51,    51,    80,    80,    52,
    52,   206,    51,    80,    80,    52,    52,   206,    51,    80,
    80,    52,    52,   206,    51,    80,   189,   190,   191,    97,
    52,    52,    51,    51,    52,    52,    51,    51,   159,   220,
   160,   221,   189,   190,   191,   238,   240,   221,   221,    63,
    64,    65,    66,    67,    68,    89,    48,    91,    95,    97,
   102,   102,   102,   104,   110,   114,   115,   118,   118,   118,
   118,   121,   122,   125,   126,   128,   130,   131,   132,   133,
   134,   137,   141,   144,   145,   146,   149,   150,   151,   153,
   161,   172,   174,   175,   176,   177,   178,   179,   180,   144,
    97,   149,   186,   194,   195,   204,   205,   210,   211,   213,
   219,   204,    97,   230,   210,   234,   236,    97,    97,   210,
   243,    97 ]

racc_action_check = [
    50,   143,    50,   143,   148,   143,   148,   181,   148,   181,
   185,   181,   185,     1,   185,   147,    33,   143,    33,     3,
   148,    33,     2,   181,     2,   203,   185,   203,     7,   203,
   224,    14,   224,    34,   224,    34,   147,    34,    34,    16,
    35,   203,    35,    17,   143,    35,   224,   148,    50,   215,
   181,    18,    75,   185,    75,    19,    75,   215,   215,   215,
    36,    37,    36,    37,    20,    36,    37,    38,   203,    38,
     4,    23,    38,   224,     4,     4,     4,     4,     4,     4,
    25,    26,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     9,   176,    15,   176,    15,   176,   176,     4,   177,
    70,   177,    70,   177,   177,   178,    71,   178,    71,   178,
   178,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,    43,    82,   196,    82,
   196,    43,   196,   196,   200,    83,   200,    83,   200,   200,
   201,   110,   201,   110,   201,   201,    43,    43,    43,    43,
    43,    43,    43,    43,    43,    43,    43,    43,    43,    43,
    43,    76,   115,    76,   115,    76,   115,   117,   138,   117,
   138,   117,   138,   164,   170,   164,   170,   164,   170,   186,
   217,   186,   217,   186,   217,   219,   221,   219,   221,   219,
   221,   227,   112,   227,   112,   227,   168,   168,   168,   168,
   118,   120,   118,   120,   135,   139,   135,   139,   140,   207,
   140,   207,   208,   208,   208,   231,   235,   231,   235,    27,
    28,    29,    30,    31,    32,    39,    40,    41,    46,    47,
    54,    56,    57,    58,    69,    73,    74,    81,    86,    87,
    88,    89,    90,    96,    97,   103,   105,   106,   107,   108,
   109,   113,   121,   122,   123,   124,   125,   126,   127,   129,
   142,   152,   154,   155,   156,   157,   158,   159,   160,   161,
   162,   165,   167,   171,   173,   179,   183,   188,   192,   202,
   206,   213,   214,   218,   220,   223,   228,   230,   234,   239,
   241,   243 ]

racc_action_pointer = [
   nil,    13,    12,    19,    61,   nil,   nil,    21,   nil,    97,
   nil,   nil,   nil,   nil,    25,   100,    20,    24,    32,    50,
    45,   nil,   nil,    52,   nil,    61,    62,   210,   225,   226,
   227,   228,   229,    13,    30,    37,    57,    58,    64,   230,
   232,   235,   nil,   132,   nil,   nil,   215,   188,   nil,   nil,
    -5,   nil,   nil,   nil,   221,   nil,   222,   223,   224,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   236,
   107,   113,   nil,   239,   238,    49,   168,   nil,   nil,   nil,
   nil,   239,   134,   142,   nil,   nil,   240,   241,   242,   211,
   210,   nil,   nil,   nil,   nil,   nil,   211,   249,   nil,   nil,
   nil,   nil,   nil,   253,   nil,   254,   255,   256,   257,   258,
   148,   nil,   199,   254,   nil,   169,   nil,   174,   207,   nil,
   208,   257,   218,   253,   263,   221,   215,   266,   nil,   267,
   nil,   nil,   nil,   nil,   nil,   211,   nil,   nil,   175,   212,
   177,   nil,   226,    -2,   nil,   nil,   nil,    -8,     1,   nil,
   nil,   nil,   251,   nil,   252,   253,   254,   255,   256,   235,
   273,   234,   229,   nil,   180,   236,   nil,   242,   158,   nil,
   181,   263,   nil,   264,   nil,   nil,    99,   106,   112,   240,
   nil,     4,   nil,   284,   nil,     7,   186,   nil,   279,   nil,
   nil,   nil,   286,   nil,   nil,   nil,   135,   nil,   nil,   nil,
   141,   147,   245,    22,   nil,   nil,   250,   178,   174,   nil,
   nil,   nil,   nil,   246,   241,     9,   nil,   187,   273,   192,
   286,   193,   nil,   275,    27,   nil,   nil,   198,   294,   nil,
   246,   184,   nil,   nil,   247,   185,   nil,   nil,   nil,   291,
   nil,   280,   nil,   250,   nil ]

racc_action_default = [
    -2,  -147,    -8,  -147,  -147,    -3,    -4,  -147,   245,  -147,
    -9,   -10,   -11,   -12,  -147,  -147,  -147,  -147,  -147,  -147,
  -147,   -24,   -25,  -147,   -29,  -147,  -147,  -147,  -147,  -147,
  -147,  -147,  -147,  -147,  -147,  -147,  -147,  -147,  -147,  -147,
  -147,  -147,    -7,  -132,  -105,  -107,  -147,  -129,  -131,   -13,
  -136,  -103,  -104,  -135,   -15,   -94,   -16,   -17,  -147,   -21,
   -26,   -30,   -33,   -36,   -39,   -40,   -41,   -42,   -43,   -44,
   -50,  -147,   -53,   -80,   -45,   -84,  -147,   -87,   -89,   -90,
  -144,   -46,   -97,  -147,  -100,  -102,   -47,   -48,   -49,  -147,
  -147,    -5,    -1,  -106,  -133,  -108,  -147,  -147,   -14,  -137,
  -138,  -139,   -91,  -147,   -18,  -147,  -147,  -147,  -147,  -147,
  -147,   -54,   -51,   -82,   -81,  -147,   -88,   -85,  -147,  -101,
   -98,  -147,   -73,  -147,  -147,  -113,  -147,  -147,   -95,  -147,
   -22,   -27,   -31,   -34,   -37,   -52,   -55,   -83,   -86,   -99,
  -147,   -57,   -70,   -71,   -74,    -6,  -134,  -109,  -110,  -114,
  -130,   -92,  -147,   -19,  -147,  -147,  -147,  -147,  -147,  -147,
  -147,   -73,  -129,   -76,  -147,  -113,  -112,  -103,  -129,  -118,
  -147,  -147,   -96,  -147,   -23,   -28,  -147,  -147,  -147,   -61,
   -58,   -72,   -75,  -147,   -79,  -111,  -147,  -115,  -145,  -122,
  -123,  -124,  -147,  -121,   -93,   -20,   -32,  -140,  -142,  -143,
   -35,   -38,   -56,   -59,   -62,   -77,  -103,  -147,  -125,  -116,
  -146,  -119,  -141,   -61,  -129,  -103,   -66,  -147,  -147,  -147,
  -145,  -147,  -127,  -147,   -60,   -63,   -64,  -147,  -147,   -69,
  -129,  -147,  -117,  -126,  -129,  -147,   -67,   -78,  -128,  -145,
   -65,  -147,  -120,  -129,   -68 ]

racc_goto_table = [
    96,    75,    53,    70,   119,    77,   111,     1,   209,   188,
   148,   207,   143,    81,    86,    87,    88,     2,   120,     4,
    73,   203,    85,    85,    85,    85,    44,   212,    54,    56,
    57,   212,   212,   196,   200,   201,    43,    92,     5,    41,
   232,   112,   119,   117,   231,   123,   116,    77,   111,   222,
   185,   181,   235,   139,    10,   224,   226,    73,    73,   242,
    93,   119,    11,    12,    13,    50,    98,   129,   173,    85,
    85,   111,   105,   154,   106,   155,   107,   156,   108,   157,
   135,   109,   138,   158,    69,    74,    77,   113,   116,   136,
   140,   202,   228,   241,    90,   142,   183,    73,   218,    73,
   127,   171,   103,   152,   147,    85,   192,    85,   223,   116,
   124,   nil,   nil,   nil,   162,   182,   nil,   nil,   nil,   168,
   nil,   187,    73,   nil,   nil,   nil,    85,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   184,   nil,   nil,   nil,   nil,
   nil,   193,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   162,   nil,   nil,   nil,   168,   208,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   225,   nil,   nil,
   nil,   nil,   nil,   nil,   214,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   237,   nil,   nil,   nil,   239,   229,   nil,
   208,   nil,   233,   nil,   nil,   214,   244,   nil,   208 ]

racc_goto_check = [
    42,    52,    35,    33,    59,    41,    34,     1,    64,    43,
    63,    44,    49,    32,    32,    32,    32,     2,    58,     3,
    35,    40,    35,    35,    35,    35,    60,    68,    15,    15,
    15,    68,    68,    21,    21,    21,     4,     5,     6,     7,
    64,    33,    59,    52,    44,     8,    41,    41,    34,    43,
    63,    49,    44,    58,     9,    40,    43,    35,    35,    64,
    60,    59,    10,    11,    12,    13,    14,    16,    17,    35,
    35,    34,    18,    19,    22,    23,    24,    25,    26,    27,
    33,    28,    52,    29,    30,    31,    41,    36,    41,    37,
    38,    39,    45,    46,    47,    48,    50,    35,    51,    35,
    54,    55,    56,    57,    62,    35,    65,    35,    66,    41,
    67,   nil,   nil,   nil,    41,    42,   nil,   nil,   nil,    41,
   nil,    42,    35,   nil,   nil,   nil,    35,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    41,   nil,   nil,   nil,   nil,
   nil,    41,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    41,   nil,   nil,   nil,    41,    41,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    42,   nil,   nil,
   nil,   nil,   nil,   nil,    41,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    42,   nil,   nil,   nil,    42,    41,   nil,
    41,   nil,    41,   nil,   nil,    41,    42,   nil,    41 ]

racc_goto_pointer = [
   nil,     7,    17,    17,    27,    -6,    36,    33,   -46,    50,
    58,    59,    60,    50,    16,    12,   -37,   -85,    13,   -57,
   nil,  -143,    14,   -56,    15,   -55,    16,   -54,    18,   -51,
    51,    51,   -22,   -30,   -64,   -13,    14,   -24,   -31,   -88,
  -158,   -29,   -47,  -159,  -175,  -124,  -143,    54,   -27,  -110,
   -67,  -107,   -33,   nil,    -2,   -50,    47,   -25,   -65,   -78,
    17,   nil,   -21,  -115,  -180,   -63,  -103,    16,  -169 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    46,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    72,    78,   nil,   nil,   nil,   nil,
   nil,   198,   nil,   nil,   nil,   nil,   nil,    47,   nil,   nil,
   nil,   nil,   nil,    79,   nil,   nil,   nil,   nil,    82,    84,
   nil,    45,   nil,   nil,   nil,   nil,   nil,   nil,   197 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 55, :_reduce_none,
  0, 56, :_reduce_none,
  2, 56, :_reduce_none,
  0, 61, :_reduce_4,
  0, 62, :_reduce_5,
  5, 60, :_reduce_6,
  2, 60, :_reduce_none,
  0, 57, :_reduce_8,
  2, 57, :_reduce_none,
  1, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 63, :_reduce_none,
  2, 63, :_reduce_13,
  3, 63, :_reduce_none,
  2, 63, :_reduce_none,
  2, 63, :_reduce_16,
  2, 63, :_reduce_17,
  0, 70, :_reduce_18,
  0, 71, :_reduce_19,
  7, 63, :_reduce_20,
  0, 72, :_reduce_21,
  0, 73, :_reduce_22,
  6, 63, :_reduce_23,
  1, 63, :_reduce_24,
  1, 63, :_reduce_none,
  0, 76, :_reduce_26,
  0, 77, :_reduce_27,
  6, 64, :_reduce_28,
  1, 64, :_reduce_none,
  0, 78, :_reduce_30,
  0, 79, :_reduce_31,
  7, 64, :_reduce_32,
  0, 80, :_reduce_33,
  0, 81, :_reduce_34,
  7, 64, :_reduce_35,
  0, 82, :_reduce_36,
  0, 83, :_reduce_37,
  7, 64, :_reduce_38,
  2, 64, :_reduce_39,
  2, 64, :_reduce_40,
  2, 64, :_reduce_41,
  2, 64, :_reduce_42,
  2, 64, :_reduce_43,
  2, 74, :_reduce_none,
  2, 74, :_reduce_45,
  2, 74, :_reduce_46,
  2, 74, :_reduce_47,
  2, 74, :_reduce_48,
  2, 74, :_reduce_49,
  1, 84, :_reduce_50,
  2, 84, :_reduce_51,
  3, 84, :_reduce_52,
  1, 87, :_reduce_53,
  2, 87, :_reduce_54,
  3, 88, :_reduce_55,
  7, 65, :_reduce_56,
  1, 92, :_reduce_57,
  3, 92, :_reduce_58,
  1, 93, :_reduce_59,
  3, 93, :_reduce_60,
  0, 94, :_reduce_61,
  1, 94, :_reduce_62,
  3, 94, :_reduce_63,
  3, 94, :_reduce_64,
  5, 94, :_reduce_65,
  0, 99, :_reduce_66,
  0, 100, :_reduce_67,
  7, 94, :_reduce_68,
  3, 94, :_reduce_69,
  4, 66, :_reduce_70,
  1, 102, :_reduce_71,
  3, 102, :_reduce_72,
  0, 103, :_reduce_73,
  1, 103, :_reduce_74,
  3, 103, :_reduce_75,
  0, 104, :_reduce_76,
  0, 105, :_reduce_77,
  7, 103, :_reduce_78,
  3, 103, :_reduce_79,
  0, 90, :_reduce_none,
  1, 90, :_reduce_none,
  0, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 85, :_reduce_84,
  2, 85, :_reduce_85,
  3, 85, :_reduce_86,
  1, 106, :_reduce_87,
  2, 106, :_reduce_88,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  0, 108, :_reduce_91,
  0, 109, :_reduce_92,
  6, 69, :_reduce_93,
  0, 110, :_reduce_94,
  0, 111, :_reduce_95,
  5, 69, :_reduce_96,
  1, 86, :_reduce_97,
  2, 86, :_reduce_98,
  3, 86, :_reduce_99,
  1, 112, :_reduce_100,
  2, 112, :_reduce_101,
  1, 113, :_reduce_none,
  1, 89, :_reduce_103,
  1, 89, :_reduce_104,
  1, 58, :_reduce_none,
  2, 58, :_reduce_none,
  1, 114, :_reduce_none,
  2, 114, :_reduce_none,
  4, 115, :_reduce_109,
  1, 116, :_reduce_110,
  3, 116, :_reduce_111,
  2, 116, :_reduce_none,
  0, 117, :_reduce_113,
  1, 117, :_reduce_114,
  3, 117, :_reduce_115,
  4, 117, :_reduce_116,
  6, 117, :_reduce_117,
  0, 119, :_reduce_118,
  0, 120, :_reduce_119,
  8, 117, :_reduce_120,
  3, 117, :_reduce_121,
  1, 97, :_reduce_122,
  1, 97, :_reduce_123,
  1, 97, :_reduce_124,
  1, 98, :_reduce_125,
  3, 98, :_reduce_126,
  2, 98, :_reduce_127,
  4, 98, :_reduce_128,
  0, 96, :_reduce_none,
  3, 96, :_reduce_130,
  1, 101, :_reduce_none,
  0, 59, :_reduce_none,
  0, 121, :_reduce_133,
  3, 59, :_reduce_134,
  1, 67, :_reduce_none,
  0, 68, :_reduce_none,
  1, 68, :_reduce_none,
  1, 68, :_reduce_none,
  1, 68, :_reduce_none,
  1, 75, :_reduce_140,
  2, 75, :_reduce_141,
  1, 122, :_reduce_none,
  1, 122, :_reduce_none,
  1, 107, :_reduce_144,
  0, 118, :_reduce_none,
  1, 118, :_reduce_none ]

racc_reduce_n = 147

racc_shift_n = 245

racc_token_table = {
  false => 0,
  :error => 1,
  :C_DECLARATION => 2,
  :CHARACTER => 3,
  :IDENT_COLON => 4,
  :IDENTIFIER => 5,
  :INTEGER => 6,
  :STRING => 7,
  :TAG => 8,
  "%%" => 9,
  "%{" => 10,
  "%}" => 11,
  "%require" => 12,
  "%expect" => 13,
  "%define" => 14,
  "%param" => 15,
  "%lex-param" => 16,
  "%parse-param" => 17,
  "%code" => 18,
  "{" => 19,
  "}" => 20,
  "%initial-action" => 21,
  "%no-stdlib" => 22,
  ";" => 23,
  "%union" => 24,
  "%destructor" => 25,
  "%printer" => 26,
  "%error-token" => 27,
  "%after-shift" => 28,
  "%before-reduce" => 29,
  "%after-reduce" => 30,
  "%after-shift-error-token" => 31,
  "%after-pop-stack" => 32,
  "%token" => 33,
  "%type" => 34,
  "%left" => 35,
  "%right" => 36,
  "%precedence" => 37,
  "%nonassoc" => 38,
  "%rule" => 39,
  "(" => 40,
  ")" => 41,
  ":" => 42,
  "," => 43,
  "|" => 44,
  "%empty" => 45,
  "%prec" => 46,
  "%inline" => 47,
  "?" => 48,
  "+" => 49,
  "*" => 50,
  "[" => 51,
  "]" => 52,
  "{...}" => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "C_DECLARATION",
  "CHARACTER",
  "IDENT_COLON",
  "IDENTIFIER",
  "INTEGER",
  "STRING",
  "TAG",
  "\"%%\"",
  "\"%{\"",
  "\"%}\"",
  "\"%require\"",
  "\"%expect\"",
  "\"%define\"",
  "\"%param\"",
  "\"%lex-param\"",
  "\"%parse-param\"",
  "\"%code\"",
  "\"{\"",
  "\"}\"",
  "\"%initial-action\"",
  "\"%no-stdlib\"",
  "\";\"",
  "\"%union\"",
  "\"%destructor\"",
  "\"%printer\"",
  "\"%error-token\"",
  "\"%after-shift\"",
  "\"%before-reduce\"",
  "\"%after-reduce\"",
  "\"%after-shift-error-token\"",
  "\"%after-pop-stack\"",
  "\"%token\"",
  "\"%type\"",
  "\"%left\"",
  "\"%right\"",
  "\"%precedence\"",
  "\"%nonassoc\"",
  "\"%rule\"",
  "\"(\"",
  "\")\"",
  "\":\"",
  "\",\"",
  "\"|\"",
  "\"%empty\"",
  "\"%prec\"",
  "\"%inline\"",
  "\"?\"",
  "\"+\"",
  "\"*\"",
  "\"[\"",
  "\"]\"",
  "\"{...}\"",
  "$start",
  "input",
  "prologue_declarations",
  "bison_declarations",
  "grammar",
  "epilogue_opt",
  "prologue_declaration",
  "@1",
  "@2",
  "bison_declaration",
  "grammar_declaration",
  "rule_declaration",
  "inline_declarations",
  "variable",
  "value",
  "params",
  "@3",
  "@4",
  "@5",
  "@6",
  "symbol_declaration",
  "generic_symlist",
  "@7",
  "@8",
  "@9",
  "@10",
  "@11",
  "@12",
  "@13",
  "@14",
  "token_declarations",
  "symbol_declarations",
  "token_declarations_for_precedence",
  "token_declaration_list",
  "token_declaration",
  "id",
  "int_opt",
  "alias",
  "rule_args",
  "rule_rhs_list",
  "rule_rhs",
  "symbol",
  "named_ref_opt",
  "parameterizing_suffix",
  "parameterizing_args",
  "@15",
  "@16",
  "id_colon",
  "inline_rhs_list",
  "inline_rhs",
  "@17",
  "@18",
  "symbol_declaration_list",
  "string_as_id",
  "@19",
  "@20",
  "@21",
  "@22",
  "token_declaration_list_for_precedence",
  "token_declaration_for_precedence",
  "rules_or_grammar_declaration",
  "rules",
  "rhs_list",
  "rhs",
  "tag_opt",
  "@23",
  "@24",
  "@25",
  "generic_symlist_item" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_4(val, _values, result)
                                begin_c_declaration("%}")
                            @grammar.prologue_first_lineno = @lexer.line

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_5(val, _values, result)
                                end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_6(val, _values, result)
                                @grammar.prologue = val[2].s_value

    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_8(val, _values, result)
     result = ""
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_13(val, _values, result)
     @grammar.expect = val[1]
    result
  end
.,.,

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'parser.y', 38)
  def _reduce_16(val, _values, result)
                             val[1].each {|token|
                           @grammar.lex_param = Grammar::Code::NoReferenceCode.new(type: :lex_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_17(val, _values, result)
                             val[1].each {|token|
                           @grammar.parse_param = Grammar::Code::NoReferenceCode.new(type: :parse_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_18(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_19(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_20(val, _values, result)
                             @grammar.add_percent_code(id: val[1], code: val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 62)
  def _reduce_21(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_22(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_23(val, _values, result)
                             @grammar.initial_action = Grammar::Code::InitialActionCode.new(type: :initial_action, token_code: val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_24(val, _values, result)
     @grammar.no_stdlib = true
    result
  end
.,.,

# reduce 25 omitted

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_26(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_27(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_28(val, _values, result)
                               @grammar.set_union(
                             Grammar::Code::NoReferenceCode.new(type: :union, token_code: val[3]),
                             val[3].line
                           )

    result
  end
.,.,

# reduce 29 omitted

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_30(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 97)
  def _reduce_31(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 101)
  def _reduce_32(val, _values, result)
                               @grammar.add_destructor(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_33(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 113)
  def _reduce_34(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 117)
  def _reduce_35(val, _values, result)
                               @grammar.add_printer(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 125)
  def _reduce_36(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 129)
  def _reduce_37(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_38(val, _values, result)
                               @grammar.add_error_token(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 141)
  def _reduce_39(val, _values, result)
                               @grammar.after_shift = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 145)
  def _reduce_40(val, _values, result)
                               @grammar.before_reduce = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 149)
  def _reduce_41(val, _values, result)
                               @grammar.after_reduce = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 153)
  def _reduce_42(val, _values, result)
                               @grammar.after_shift_error_token = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 157)
  def _reduce_43(val, _values, result)
                               @grammar.after_pop_stack = val[1]

    result
  end
.,.,

# reduce 44 omitted

module_eval(<<'.,.,', 'parser.y', 163)
  def _reduce_45(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              @grammar.add_type(id: id, tag: hash[:tag])
                            }
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 171)
  def _reduce_46(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_left(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 181)
  def _reduce_47(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_right(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 191)
  def _reduce_48(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_precedence(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 201)
  def _reduce_49(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_nonassoc(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 212)
  def _reduce_50(val, _values, result)
                              val[0].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: nil, replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 218)
  def _reduce_51(val, _values, result)
                              val[1].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[0], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_52(val, _values, result)
                              val[2].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[1], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 229)
  def _reduce_53(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 230)
  def _reduce_54(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_55(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 236)
  def _reduce_56(val, _values, result)
                            rule = Grammar::ParameterizingRule::Rule.new(val[1].s_value, val[3], val[6])
                        @grammar.add_parameterizing_rule(rule)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 240)
  def _reduce_57(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 241)
  def _reduce_58(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 245)
  def _reduce_59(val, _values, result)
                      builder = val[0]
                  result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 250)
  def _reduce_60(val, _values, result)
                      builder = val[2]
                  result = val[0].append(builder)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 256)
  def _reduce_61(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRule::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 261)
  def _reduce_62(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRule::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 266)
  def _reduce_63(val, _values, result)
                  token = val[1]
              token.alias_name = val[2]
              builder = val[0]
              builder.symbols << token
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 274)
  def _reduce_64(val, _values, result)
                    builder = val[0]
                builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], location: @lexer.location, args: [val[1]])
                result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 280)
  def _reduce_65(val, _values, result)
                    builder = val[0]
                builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[3])
                result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 286)
  def _reduce_66(val, _values, result)
                  if @prec_seen
                on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
                @code_after_prec = true
              end
              begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 294)
  def _reduce_67(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 298)
  def _reduce_68(val, _values, result)
                  user_code = val[3]
              user_code.alias_name = val[6]
              builder = val[0]
              builder.user_code = user_code
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 306)
  def _reduce_69(val, _values, result)
                  sym = @grammar.find_symbol_by_id!(val[2])
              @prec_seen = true
              builder = val[0]
              builder.precedence_sym = sym
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 315)
  def _reduce_70(val, _values, result)
                              rule = Grammar::Inline::Rule.new(val[1].s_value, val[3])
                          @grammar.add_inline_rule(rule)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 321)
  def _reduce_71(val, _values, result)
                        builder = val[0]
                    result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 326)
  def _reduce_72(val, _values, result)
                        builder = val[2]
                    result = val[0].append(builder)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 332)
  def _reduce_73(val, _values, result)
                  reset_precs
              result = Grammar::Inline::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 337)
  def _reduce_74(val, _values, result)
                  reset_precs
              result = Grammar::Inline::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 342)
  def _reduce_75(val, _values, result)
                  token = val[1]
              token.alias_name = val[2]
              builder = val[0]
              builder.symbols << token
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 350)
  def _reduce_76(val, _values, result)
                  if @prec_seen
                on_action_error("multiple User_code after %prec", val[0]) if @code_after_prec
                @code_after_prec = true
              end
              begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 358)
  def _reduce_77(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 362)
  def _reduce_78(val, _values, result)
                  user_code = val[3]
              user_code.alias_name = val[6]
              builder = val[0]
              builder.user_code = user_code
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 370)
  def _reduce_79(val, _values, result)
                  sym = @grammar.find_symbol_by_id!(val[2])
              @prec_seen = true
              builder = val[0]
              builder.precedence_sym = sym
              result = builder

    result
  end
.,.,

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

module_eval(<<'.,.,', 'parser.y', 385)
  def _reduce_84(val, _values, result)
                               result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 389)
  def _reduce_85(val, _values, result)
                               result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 393)
  def _reduce_86(val, _values, result)
                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 396)
  def _reduce_87(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 397)
  def _reduce_88(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 89 omitted

# reduce 90 omitted

module_eval(<<'.,.,', 'parser.y', 404)
  def _reduce_91(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 408)
  def _reduce_92(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 412)
  def _reduce_93(val, _values, result)
                  result = val[0].append(val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 416)
  def _reduce_94(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 420)
  def _reduce_95(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 424)
  def _reduce_96(val, _values, result)
                  result = [val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 429)
  def _reduce_97(val, _values, result)
                                             result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 433)
  def _reduce_98(val, _values, result)
                                             result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 437)
  def _reduce_99(val, _values, result)
                                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 440)
  def _reduce_100(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 441)
  def _reduce_101(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 102 omitted

module_eval(<<'.,.,', 'parser.y', 445)
  def _reduce_103(val, _values, result)
     on_action_error("ident after %prec", val[0]) if @prec_seen
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 446)
  def _reduce_104(val, _values, result)
     on_action_error("char after %prec", val[0]) if @prec_seen
    result
  end
.,.,

# reduce 105 omitted

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

module_eval(<<'.,.,', 'parser.y', 456)
  def _reduce_109(val, _values, result)
                 lhs = val[0]
             lhs.alias_name = val[1]
             val[3].each do |builder|
               builder.lhs = lhs
               builder.complete_input
               @grammar.add_rule_builder(builder)
             end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 467)
  def _reduce_110(val, _values, result)
                    builder = val[0]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 475)
  def _reduce_111(val, _values, result)
                    builder = val[2]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = val[0].append(builder)

    result
  end
.,.,

# reduce 112 omitted

module_eval(<<'.,.,', 'parser.y', 485)
  def _reduce_113(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 490)
  def _reduce_114(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 495)
  def _reduce_115(val, _values, result)
               token = val[1]
           token.alias_name = val[2]
           builder = val[0]
           builder.add_rhs(token)
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 503)
  def _reduce_116(val, _values, result)
               token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], location: @lexer.location, args: [val[1]], lhs_tag: val[3])
           builder = val[0]
           builder.add_rhs(token)
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 511)
  def _reduce_117(val, _values, result)
               token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[3], lhs_tag: val[5])
           builder = val[0]
           builder.add_rhs(token)
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 519)
  def _reduce_118(val, _values, result)
               if @prec_seen
             on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
             @code_after_prec = true
           end
           begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 527)
  def _reduce_119(val, _values, result)
               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 531)
  def _reduce_120(val, _values, result)
               user_code = val[3]
           user_code.alias_name = val[6]
           user_code.tag = val[7]
           builder = val[0]
           builder.user_code = user_code
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 540)
  def _reduce_121(val, _values, result)
               sym = @grammar.find_symbol_by_id!(val[2])
           @prec_seen = true
           builder = val[0]
           builder.precedence_sym = sym
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 547)
  def _reduce_122(val, _values, result)
     result = "option"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 548)
  def _reduce_123(val, _values, result)
     result = "nonempty_list"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 549)
  def _reduce_124(val, _values, result)
     result = "list"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 551)
  def _reduce_125(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 552)
  def _reduce_126(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 553)
  def _reduce_127(val, _values, result)
     result = [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 554)
  def _reduce_128(val, _values, result)
     result = [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[0].s_value, location: @lexer.location, args: val[2])]
    result
  end
.,.,

# reduce 129 omitted

module_eval(<<'.,.,', 'parser.y', 557)
  def _reduce_130(val, _values, result)
     result = val[1].s_value
    result
  end
.,.,

# reduce 131 omitted

# reduce 132 omitted

module_eval(<<'.,.,', 'parser.y', 564)
  def _reduce_133(val, _values, result)
                        begin_c_declaration('\Z')
                    @grammar.epilogue_first_lineno = @lexer.line + 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 569)
  def _reduce_134(val, _values, result)
                        end_c_declaration
                    @grammar.epilogue = val[2].s_value

    result
  end
.,.,

# reduce 135 omitted

# reduce 136 omitted

# reduce 137 omitted

# reduce 138 omitted

# reduce 139 omitted

module_eval(<<'.,.,', 'parser.y', 580)
  def _reduce_140(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 581)
  def _reduce_141(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 142 omitted

# reduce 143 omitted

module_eval(<<'.,.,', 'parser.y', 586)
  def _reduce_144(val, _values, result)
     result = Lrama::Lexer::Token::Ident.new(s_value: val[0])
    result
  end
.,.,

# reduce 145 omitted

# reduce 146 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Lrama
