#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "parser.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.7.3'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError # :nodoc:
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is a LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end
module Lrama
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 488)

include Lrama::Report::Duration

def initialize(text, path, debug = false)
  @text = text
  @path = path
  @yydebug = debug
  @rule_counter = Lrama::Grammar::Counter.new(0)
  @midrule_action_counter = Lrama::Grammar::Counter.new(1)
end

def parse
  report_duration(:parse) do
    @lexer = Lrama::Lexer.new(@text)
    @grammar = Lrama::Grammar.new(@rule_counter)
    @precedence_number = 0
    reset_precs
    do_parse
    @grammar.prepare
    @grammar.validate!
    @grammar
  end
end

def next_token
  @lexer.next_token
end

def on_error(error_token_id, error_value, value_stack)
  if error_value.is_a?(Lrama::Lexer::Token)
    line = error_value.first_line
    first_column = error_value.first_column
    last_column = error_value.last_column
    value = "'#{error_value.s_value}'"
  else
    line = @lexer.line
    first_column = @lexer.head_column
    last_column = @lexer.column
    value = error_value.inspect
  end

  raise ParseError, <<~ERROR
    #{@path}:#{line}:#{first_column}: parse error on value #{value} (#{token_to_str(error_token_id) || '?'})
    #{@text.split("\n")[line - 1]}
    #{carrets(first_column, last_column)}
  ERROR
end

def on_action_error(error_message, error_value)
  if error_value.is_a?(Lrama::Lexer::Token)
    line = error_value.first_line
    first_column = error_value.first_column
    last_column = error_value.last_column
  else
    line = @lexer.line
    first_column = @lexer.head_column
    last_column = @lexer.column
  end

  raise ParseError, <<~ERROR
    #{@path}:#{line}: #{error_message}
    #{@text.split("\n")[line - 1]}
    #{carrets(first_column, last_column)}
  ERROR
end

private

def reset_precs
  @prec_seen = false
  @code_after_prec = false
end

def begin_c_declaration(end_symbol)
  @lexer.status = :c_declaration
  @lexer.end_symbol = end_symbol
end

def end_c_declaration
  @lexer.status = :initial
  @lexer.end_symbol = nil
end

def carrets(first_column, last_column)
  ' ' * (first_column + 1) + '^' * (last_column - first_column)
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    85,    44,    86,   145,   144,    67,    44,    44,   145,    43,
    67,    67,    44,     6,    43,     7,    67,   147,   161,    44,
   143,    43,   147,   187,    58,   162,   163,   164,   187,     3,
    44,    40,    43,     8,    67,    63,    34,    44,   148,    43,
    41,    87,    40,   148,   188,    47,    44,    80,    43,   188,
    21,    23,    24,    25,    26,    27,    28,    29,    30,    31,
    47,    21,    23,    24,    25,    26,    27,    28,    29,    30,
    31,     9,    44,    47,    43,    13,    14,    15,    16,    17,
    18,    50,    51,    19,    20,    21,    23,    24,    25,    26,
    27,    28,    29,    30,    31,    32,    44,    44,    43,    43,
    52,    70,    70,    44,    44,    43,    43,    53,    70,    70,
    44,    44,    43,    43,    67,   173,    44,    44,    43,    43,
    67,   173,    44,    44,    43,    43,    67,   173,    44,    44,
    43,    43,    67,   173,    44,    44,    43,    43,    67,   173,
    44,    44,    43,    43,    67,   173,    44,    44,    43,    43,
    67,    67,    44,    44,    43,    43,    67,    67,    44,    44,
    43,    43,    67,    67,    44,    44,    43,    43,    67,    67,
    44,    44,    43,    43,    67,    44,   141,    43,   142,   189,
    54,   190,    55,    76,    77,    81,    83,    88,    88,    88,
    90,    96,   100,   101,   104,   104,   104,   104,   107,   110,
   111,   113,   115,   116,   117,   118,   119,   122,   126,   127,
   128,   131,   132,   133,   135,   150,   152,   153,   154,   155,
   156,   157,   158,   131,    83,   168,   169,   178,   180,   183,
   185,   178,    83,   180,   198,   199,    83,   202,    83 ]

racc_action_check = [
    42,   130,    42,   130,   129,   130,   159,   177,   159,   177,
   159,   177,   192,     2,   192,     2,   192,   130,   145,    26,
   129,    26,   159,   177,    26,   145,   145,   145,   192,     1,
    27,     9,    27,     3,    27,    27,     7,    14,   130,    14,
    13,    42,    35,   159,   177,    15,    57,    35,    57,   192,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
    16,    35,    35,    35,    35,    35,    35,    35,    35,    35,
    35,     4,    58,    17,    58,     4,     4,     4,     4,     4,
     4,    18,    19,     4,     4,     4,     4,     4,     4,     4,
     4,     4,     4,     4,     4,     4,    28,    29,    28,    29,
    21,    28,    29,    30,    31,    30,    31,    23,    30,    31,
   154,    69,   154,    69,   154,   154,   155,    70,   155,    70,
   155,   155,   156,    96,   156,    96,   156,   156,   170,    98,
   170,    98,   170,   170,   174,   104,   174,   104,   174,   174,
   175,   106,   175,   106,   175,   175,    62,    63,    62,    63,
    62,    63,   101,   103,   101,   103,   101,   103,   123,   148,
   123,   148,   123,   148,   161,   188,   161,   188,   161,   188,
   190,   120,   190,   120,   190,   124,   125,   124,   125,   181,
    24,   181,    25,    32,    33,    38,    39,    46,    48,    49,
    50,    56,    60,    61,    68,    73,    74,    75,    76,    82,
    83,    89,    91,    92,    93,    94,    95,    99,   107,   108,
   109,   110,   111,   112,   114,   134,   136,   137,   138,   139,
   140,   141,   142,   143,   146,   149,   151,   157,   160,   166,
   176,   185,   186,   189,   191,   194,   198,   201,   202 ]

racc_action_pointer = [
   nil,    29,     3,    33,    62,   nil,   nil,    29,   nil,    27,
   nil,   nil,   nil,    34,    34,    26,    41,    54,    76,    63,
   nil,    81,   nil,    88,   161,   163,    16,    27,    93,    94,
   100,   101,   178,   182,   nil,    38,   nil,   nil,   163,   142,
   nil,   nil,    -5,   nil,   nil,   nil,   168,   nil,   169,   170,
   171,   nil,   nil,   nil,   nil,   nil,   183,    43,    69,   nil,
   186,   185,   143,   144,   nil,   nil,   nil,   nil,   186,   108,
   114,   nil,   nil,   187,   188,   189,   164,   nil,   nil,   nil,
   nil,   nil,   163,   195,   nil,   nil,   nil,   nil,   nil,   199,
   nil,   200,   201,   202,   203,   204,   120,   nil,   126,   200,
   nil,   149,   nil,   150,   132,   nil,   138,   203,   198,   208,
   172,   167,   211,   nil,   212,   nil,   nil,   nil,   nil,   nil,
   168,   nil,   nil,   155,   172,   141,   nil,   nil,   nil,   -18,
    -2,   nil,   nil,   nil,   195,   nil,   196,   197,   198,   199,
   200,   185,   217,   184,   nil,   -16,   180,   nil,   156,   205,
   nil,   206,   nil,   nil,   107,   113,   119,   188,   nil,     3,
   220,   161,   nil,   nil,   nil,   nil,   227,   nil,   nil,   nil,
   125,   nil,   nil,   nil,   131,   137,   192,     4,   nil,   nil,
   nil,   144,   nil,   nil,   nil,   192,   188,   nil,   162,   225,
   167,   214,     9,   nil,   233,   nil,   nil,   nil,   192,   nil,
   nil,   217,   194,   nil ]

racc_action_default = [
    -2,  -126,    -8,  -126,  -126,    -3,    -4,  -126,   204,  -126,
    -9,   -10,   -11,  -126,  -126,  -126,  -126,  -126,  -126,  -126,
   -23,  -126,   -27,  -126,  -126,  -126,  -126,  -126,  -126,  -126,
  -126,  -126,  -126,  -126,    -7,  -111,   -86,   -88,  -126,  -108,
  -110,   -12,  -115,   -84,   -85,  -114,   -14,   -75,   -15,   -16,
  -126,   -20,   -24,   -28,   -31,   -34,   -37,   -43,  -126,   -46,
   -61,   -38,   -65,  -126,   -68,   -70,   -71,  -123,   -39,   -78,
  -126,   -81,   -83,   -40,   -41,   -42,  -126,    -5,    -1,   -87,
  -112,   -89,  -126,  -126,   -13,  -116,  -117,  -118,   -72,  -126,
   -17,  -126,  -126,  -126,  -126,  -126,  -126,   -47,   -44,   -63,
   -62,  -126,   -69,   -66,  -126,   -82,   -79,  -126,  -126,  -126,
   -94,  -126,  -126,   -76,  -126,   -21,   -25,   -29,   -32,   -35,
   -45,   -48,   -64,   -67,   -80,  -126,   -50,    -6,  -113,   -90,
   -91,   -95,  -109,   -73,  -126,   -18,  -126,  -126,  -126,  -126,
  -126,  -126,  -126,   -94,   -93,   -84,  -108,   -99,  -126,  -126,
   -77,  -126,   -22,   -26,  -126,  -126,  -126,   -54,   -51,   -92,
  -124,  -126,  -103,  -104,  -105,   -96,  -126,  -102,   -74,   -19,
   -30,  -119,  -121,  -122,   -33,   -36,   -49,   -52,   -55,   -97,
  -125,  -126,  -106,  -100,  -120,   -54,  -108,   -57,  -126,  -124,
  -126,  -126,   -53,   -56,  -126,   -60,   -98,  -107,  -108,   -58,
  -101,  -126,  -108,   -59 ]

racc_goto_table = [
    64,    82,    57,    45,    62,   105,   130,    97,   179,   106,
   177,    68,    73,    74,    75,    60,     1,    72,    72,    72,
    72,   184,     2,    36,     4,   184,   184,    46,    48,    49,
   170,   174,   175,    35,    98,   102,    64,   196,   192,   159,
   103,    78,   105,   124,     5,    33,    60,    60,    97,    79,
   108,    10,    11,    12,    42,    84,   114,   151,    72,    72,
   105,    91,   136,    92,   137,    93,   138,    94,   139,    95,
    97,   140,   120,    56,    64,    61,   102,    99,   123,   121,
   125,   176,   194,   201,   112,    60,   149,    60,    89,   134,
   129,   160,   181,    72,   166,    72,   102,   191,   109,   nil,
   nil,   nil,   nil,   146,   nil,   nil,   nil,   nil,   165,    60,
   nil,   nil,   nil,    72,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   167,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   146,   nil,   182,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   193,   nil,
   186,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   200,   195,   nil,   197,   203,   186 ]

racc_goto_check = [
    40,    41,    32,    34,    44,    51,    56,    33,    58,    50,
    39,    31,    31,    31,    31,    34,     1,    34,    34,    34,
    34,    63,     2,    52,     3,    63,    63,    14,    14,    14,
    20,    20,    20,     4,    32,    40,    40,    58,    39,    56,
    44,     5,    51,    50,     6,     7,    34,    34,    33,    52,
     8,     9,    10,    11,    12,    13,    15,    16,    34,    34,
    51,    17,    18,    21,    22,    23,    24,    25,    26,    27,
    33,    28,    32,    29,    40,    30,    40,    35,    44,    36,
    37,    38,    42,    43,    46,    34,    47,    34,    48,    49,
    55,    57,    59,    34,    60,    34,    40,    61,    62,   nil,
   nil,   nil,   nil,    40,   nil,   nil,   nil,   nil,    41,    34,
   nil,   nil,   nil,    34,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    40,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    40,   nil,    40,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    41,   nil,
    40,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    41,    40,   nil,    40,    41,    40 ]

racc_goto_pointer = [
   nil,    16,    22,    22,    24,     6,    42,    39,   -27,    47,
    48,    49,    40,    13,    12,   -34,   -78,    10,   -53,   nil,
  -124,    11,   -52,    12,   -51,    13,   -50,    14,   -48,    47,
    48,   -17,   -24,   -50,   -11,    17,   -20,   -27,   -76,  -147,
   -27,   -38,  -105,  -116,   -23,   nil,    -4,   -47,    41,   -24,
   -61,   -64,    14,   nil,   nil,   -20,  -104,   -54,  -152,   -69,
   -53,   -86,    18,  -149 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    38,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    59,    65,   nil,   nil,   nil,   nil,   nil,
   172,   nil,   nil,   nil,   nil,    66,   nil,   nil,   nil,   nil,
    69,    71,   nil,    37,    39,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   171 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 48, :_reduce_none,
  0, 49, :_reduce_none,
  2, 49, :_reduce_none,
  0, 54, :_reduce_4,
  0, 55, :_reduce_5,
  5, 53, :_reduce_6,
  2, 53, :_reduce_none,
  0, 50, :_reduce_8,
  2, 50, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  2, 56, :_reduce_12,
  3, 56, :_reduce_none,
  2, 56, :_reduce_none,
  2, 56, :_reduce_15,
  2, 56, :_reduce_16,
  0, 62, :_reduce_17,
  0, 63, :_reduce_18,
  7, 56, :_reduce_19,
  0, 64, :_reduce_20,
  0, 65, :_reduce_21,
  6, 56, :_reduce_22,
  1, 56, :_reduce_none,
  0, 68, :_reduce_24,
  0, 69, :_reduce_25,
  6, 57, :_reduce_26,
  1, 57, :_reduce_none,
  0, 70, :_reduce_28,
  0, 71, :_reduce_29,
  7, 57, :_reduce_none,
  0, 72, :_reduce_31,
  0, 73, :_reduce_32,
  7, 57, :_reduce_33,
  0, 74, :_reduce_34,
  0, 75, :_reduce_35,
  7, 57, :_reduce_36,
  2, 66, :_reduce_none,
  2, 66, :_reduce_38,
  2, 66, :_reduce_39,
  2, 66, :_reduce_40,
  2, 66, :_reduce_41,
  2, 66, :_reduce_42,
  1, 76, :_reduce_43,
  2, 76, :_reduce_44,
  3, 76, :_reduce_45,
  1, 79, :_reduce_46,
  2, 79, :_reduce_47,
  3, 80, :_reduce_48,
  7, 58, :_reduce_49,
  1, 84, :_reduce_50,
  3, 84, :_reduce_51,
  1, 85, :_reduce_52,
  3, 85, :_reduce_53,
  0, 86, :_reduce_54,
  1, 86, :_reduce_55,
  3, 86, :_reduce_56,
  0, 89, :_reduce_57,
  0, 90, :_reduce_58,
  7, 86, :_reduce_59,
  3, 86, :_reduce_60,
  0, 82, :_reduce_none,
  1, 82, :_reduce_none,
  0, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 77, :_reduce_65,
  2, 77, :_reduce_66,
  3, 77, :_reduce_67,
  1, 91, :_reduce_68,
  2, 91, :_reduce_69,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  0, 93, :_reduce_72,
  0, 94, :_reduce_73,
  6, 61, :_reduce_74,
  0, 95, :_reduce_75,
  0, 96, :_reduce_76,
  5, 61, :_reduce_77,
  1, 78, :_reduce_78,
  2, 78, :_reduce_79,
  3, 78, :_reduce_80,
  1, 97, :_reduce_81,
  2, 97, :_reduce_82,
  1, 98, :_reduce_none,
  1, 81, :_reduce_84,
  1, 81, :_reduce_85,
  1, 51, :_reduce_none,
  2, 51, :_reduce_none,
  1, 99, :_reduce_none,
  2, 99, :_reduce_none,
  4, 100, :_reduce_90,
  1, 102, :_reduce_91,
  3, 102, :_reduce_92,
  2, 102, :_reduce_none,
  0, 103, :_reduce_94,
  1, 103, :_reduce_95,
  3, 103, :_reduce_96,
  4, 103, :_reduce_97,
  6, 103, :_reduce_98,
  0, 107, :_reduce_99,
  0, 108, :_reduce_100,
  7, 103, :_reduce_101,
  3, 103, :_reduce_102,
  1, 104, :_reduce_none,
  1, 104, :_reduce_none,
  1, 104, :_reduce_none,
  1, 106, :_reduce_106,
  3, 106, :_reduce_107,
  0, 88, :_reduce_none,
  3, 88, :_reduce_109,
  1, 101, :_reduce_none,
  0, 52, :_reduce_none,
  0, 109, :_reduce_112,
  3, 52, :_reduce_113,
  1, 59, :_reduce_none,
  0, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 67, :_reduce_119,
  2, 67, :_reduce_120,
  1, 110, :_reduce_none,
  1, 110, :_reduce_none,
  1, 92, :_reduce_123,
  0, 105, :_reduce_none,
  1, 105, :_reduce_none ]

racc_reduce_n = 126

racc_shift_n = 204

racc_token_table = {
  false => 0,
  :error => 1,
  :C_DECLARATION => 2,
  :CHARACTER => 3,
  :IDENT_COLON => 4,
  :IDENTIFIER => 5,
  :INTEGER => 6,
  :STRING => 7,
  :TAG => 8,
  "%%" => 9,
  "%{" => 10,
  "%}" => 11,
  "%require" => 12,
  "%expect" => 13,
  "%define" => 14,
  "%param" => 15,
  "%lex-param" => 16,
  "%parse-param" => 17,
  "%code" => 18,
  "{" => 19,
  "}" => 20,
  "%initial-action" => 21,
  ";" => 22,
  "%union" => 23,
  "%destructor" => 24,
  "%printer" => 25,
  "%error-token" => 26,
  "%token" => 27,
  "%type" => 28,
  "%left" => 29,
  "%right" => 30,
  "%precedence" => 31,
  "%nonassoc" => 32,
  "%rule" => 33,
  "(" => 34,
  ")" => 35,
  ":" => 36,
  "," => 37,
  "|" => 38,
  "%empty" => 39,
  "%prec" => 40,
  "?" => 41,
  "+" => 42,
  "*" => 43,
  "[" => 44,
  "]" => 45,
  "{...}" => 46 }

racc_nt_base = 47

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "C_DECLARATION",
  "CHARACTER",
  "IDENT_COLON",
  "IDENTIFIER",
  "INTEGER",
  "STRING",
  "TAG",
  "\"%%\"",
  "\"%{\"",
  "\"%}\"",
  "\"%require\"",
  "\"%expect\"",
  "\"%define\"",
  "\"%param\"",
  "\"%lex-param\"",
  "\"%parse-param\"",
  "\"%code\"",
  "\"{\"",
  "\"}\"",
  "\"%initial-action\"",
  "\";\"",
  "\"%union\"",
  "\"%destructor\"",
  "\"%printer\"",
  "\"%error-token\"",
  "\"%token\"",
  "\"%type\"",
  "\"%left\"",
  "\"%right\"",
  "\"%precedence\"",
  "\"%nonassoc\"",
  "\"%rule\"",
  "\"(\"",
  "\")\"",
  "\":\"",
  "\",\"",
  "\"|\"",
  "\"%empty\"",
  "\"%prec\"",
  "\"?\"",
  "\"+\"",
  "\"*\"",
  "\"[\"",
  "\"]\"",
  "\"{...}\"",
  "$start",
  "input",
  "prologue_declarations",
  "bison_declarations",
  "grammar",
  "epilogue_opt",
  "prologue_declaration",
  "@1",
  "@2",
  "bison_declaration",
  "grammar_declaration",
  "rule_declaration",
  "variable",
  "value",
  "params",
  "@3",
  "@4",
  "@5",
  "@6",
  "symbol_declaration",
  "generic_symlist",
  "@7",
  "@8",
  "@9",
  "@10",
  "@11",
  "@12",
  "@13",
  "@14",
  "token_declarations",
  "symbol_declarations",
  "token_declarations_for_precedence",
  "token_declaration_list",
  "token_declaration",
  "id",
  "int_opt",
  "alias",
  "rule_args",
  "rule_rhs_list",
  "rule_rhs",
  "symbol",
  "named_ref_opt",
  "@15",
  "@16",
  "symbol_declaration_list",
  "string_as_id",
  "@17",
  "@18",
  "@19",
  "@20",
  "token_declaration_list_for_precedence",
  "token_declaration_for_precedence",
  "rules_or_grammar_declaration",
  "rules",
  "id_colon",
  "rhs_list",
  "rhs",
  "parameterizing_suffix",
  "tag_opt",
  "parameterizing_args",
  "@21",
  "@22",
  "@23",
  "generic_symlist_item" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_4(val, _values, result)
                                begin_c_declaration("%}")
                            @grammar.prologue_first_lineno = @lexer.line

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_5(val, _values, result)
                                end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_6(val, _values, result)
                                @grammar.prologue = val[2].s_value

    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_8(val, _values, result)
     result = ""
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_12(val, _values, result)
     @grammar.expect = val[1]
    result
  end
.,.,

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_15(val, _values, result)
                             val[1].each {|token|
                           @grammar.lex_param = Grammar::Code::NoReferenceCode.new(type: :lex_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_16(val, _values, result)
                             val[1].each {|token|
                           @grammar.parse_param = Grammar::Code::NoReferenceCode.new(type: :parse_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_17(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_18(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_19(val, _values, result)
                             @grammar.add_percent_code(id: val[1], code: val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_20(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_21(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_22(val, _values, result)
                             @grammar.initial_action = Grammar::Code::InitialActionCode.new(type: :initial_action, token_code: val[3])

    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_24(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_25(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_26(val, _values, result)
                               @grammar.set_union(
                             Grammar::Code::NoReferenceCode.new(type: :union, token_code: val[3]),
                             val[3].line
                           )

    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_28(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_29(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

# reduce 30 omitted

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_31(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 104)
  def _reduce_32(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 108)
  def _reduce_33(val, _values, result)
                               @grammar.add_printer(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_34(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_35(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 124)
  def _reduce_36(val, _values, result)
                               @grammar.add_error_token(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

# reduce 37 omitted

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_38(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              @grammar.add_type(id: id, tag: hash[:tag])
                            }
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 142)
  def _reduce_39(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_left(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 152)
  def _reduce_40(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_right(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 162)
  def _reduce_41(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_precedence(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_42(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_nonassoc(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 183)
  def _reduce_43(val, _values, result)
                              val[0].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: nil, replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 189)
  def _reduce_44(val, _values, result)
                              val[1].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[0], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 195)
  def _reduce_45(val, _values, result)
                              val[2].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[1], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 200)
  def _reduce_46(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 201)
  def _reduce_47(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 203)
  def _reduce_48(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 207)
  def _reduce_49(val, _values, result)
                            builder = Grammar::ParameterizingRuleBuilder.new(val[1].s_value, val[3], val[6])
                        @grammar.add_parameterizing_rule_builder(builder)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 211)
  def _reduce_50(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 212)
  def _reduce_51(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 216)
  def _reduce_52(val, _values, result)
                      builder = val[0]
                  result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 221)
  def _reduce_53(val, _values, result)
                      builder = val[2]
                  result = val[0].append(builder)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_54(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRuleRhsBuilder.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_55(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRuleRhsBuilder.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 237)
  def _reduce_56(val, _values, result)
                  token = val[1]
              token.alias_name = val[2]
              builder = val[0]
              builder.symbols << token
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 245)
  def _reduce_57(val, _values, result)
                  if @prec_seen
                on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
                @code_after_prec = true
              end
              begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 253)
  def _reduce_58(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 257)
  def _reduce_59(val, _values, result)
                  user_code = val[3]
              user_code.alias_name = val[6]
              builder = val[0]
              builder.user_code = user_code
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 265)
  def _reduce_60(val, _values, result)
                  sym = @grammar.find_symbol_by_id!(val[2])
              @prec_seen = true
              builder = val[0]
              builder.precedence_sym = sym
              result = builder

    result
  end
.,.,

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

module_eval(<<'.,.,', 'parser.y', 280)
  def _reduce_65(val, _values, result)
                               result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 284)
  def _reduce_66(val, _values, result)
                               result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 288)
  def _reduce_67(val, _values, result)
                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 291)
  def _reduce_68(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 292)
  def _reduce_69(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 70 omitted

# reduce 71 omitted

module_eval(<<'.,.,', 'parser.y', 299)
  def _reduce_72(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 303)
  def _reduce_73(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 307)
  def _reduce_74(val, _values, result)
                  result = val[0].append(val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 311)
  def _reduce_75(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 315)
  def _reduce_76(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 319)
  def _reduce_77(val, _values, result)
                  result = [val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 324)
  def _reduce_78(val, _values, result)
                                             result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 328)
  def _reduce_79(val, _values, result)
                                             result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 332)
  def _reduce_80(val, _values, result)
                                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 335)
  def _reduce_81(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 336)
  def _reduce_82(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 83 omitted

module_eval(<<'.,.,', 'parser.y', 340)
  def _reduce_84(val, _values, result)
     on_action_error("ident after %prec", val[0]) if @prec_seen
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 341)
  def _reduce_85(val, _values, result)
     on_action_error("char after %prec", val[0]) if @prec_seen
    result
  end
.,.,

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

# reduce 89 omitted

module_eval(<<'.,.,', 'parser.y', 351)
  def _reduce_90(val, _values, result)
                 lhs = val[0]
             lhs.alias_name = val[1]
             val[3].each do |builder|
               builder.lhs = lhs
               builder.complete_input
               @grammar.add_rule_builder(builder)
             end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 362)
  def _reduce_91(val, _values, result)
                    builder = val[0]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 370)
  def _reduce_92(val, _values, result)
                    builder = val[2]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = val[0].append(builder)

    result
  end
.,.,

# reduce 93 omitted

module_eval(<<'.,.,', 'parser.y', 380)
  def _reduce_94(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 385)
  def _reduce_95(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 390)
  def _reduce_96(val, _values, result)
               token = val[1]
           token.alias_name = val[2]
           builder = val[0]
           builder.add_rhs(token)
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 398)
  def _reduce_97(val, _values, result)
               token = Lrama::Lexer::Token::Parameterizing.new(s_value: val[2], location: @lexer.location, args: [val[1]])
           builder = val[0]
           builder.add_rhs(token)
           builder.lhs_tag = val[3]
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 407)
  def _reduce_98(val, _values, result)
               token = Lrama::Lexer::Token::Parameterizing.new(s_value: val[1].s_value, location: @lexer.location, args: val[3])
           builder = val[0]
           builder.add_rhs(token)
           builder.lhs_tag = val[5]
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 416)
  def _reduce_99(val, _values, result)
               if @prec_seen
             on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
             @code_after_prec = true
           end
           begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 424)
  def _reduce_100(val, _values, result)
               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 428)
  def _reduce_101(val, _values, result)
               user_code = val[3]
           user_code.alias_name = val[6]
           builder = val[0]
           builder.user_code = user_code
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 436)
  def _reduce_102(val, _values, result)
               sym = @grammar.find_symbol_by_id!(val[2])
           @prec_seen = true
           builder = val[0]
           builder.precedence_sym = sym
           result = builder

    result
  end
.,.,

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

module_eval(<<'.,.,', 'parser.y', 447)
  def _reduce_106(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 448)
  def _reduce_107(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

# reduce 108 omitted

module_eval(<<'.,.,', 'parser.y', 451)
  def _reduce_109(val, _values, result)
     result = val[1].s_value
    result
  end
.,.,

# reduce 110 omitted

# reduce 111 omitted

module_eval(<<'.,.,', 'parser.y', 458)
  def _reduce_112(val, _values, result)
                        begin_c_declaration('\Z')
                    @grammar.epilogue_first_lineno = @lexer.line + 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 463)
  def _reduce_113(val, _values, result)
                        end_c_declaration
                    @grammar.epilogue = val[2].s_value

    result
  end
.,.,

# reduce 114 omitted

# reduce 115 omitted

# reduce 116 omitted

# reduce 117 omitted

# reduce 118 omitted

module_eval(<<'.,.,', 'parser.y', 474)
  def _reduce_119(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 475)
  def _reduce_120(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 121 omitted

# reduce 122 omitted

module_eval(<<'.,.,', 'parser.y', 480)
  def _reduce_123(val, _values, result)
     result = Lrama::Lexer::Token::Ident.new(s_value: val[0])
    result
  end
.,.,

# reduce 124 omitted

# reduce 125 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Lrama
