module Lrama
  class State
    class Shift
      @next_sym: Grammar::Symbol
      @next_items: Array[States::Item]

      attr_reader next_sym: Grammar::Symbol
      attr_reader next_items: Array[States::Item]
      attr_accessor not_selected: bool

      def initialize: (Grammar::Symbol next_sym, Array[States::Item] next_items) -> void
    end
  end
end
